apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.23.0 (bc7d9f4f)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.23.0 (bc7d9f4f)
      creationTimestamp: null
      labels:
        io.kompose.service: mysql
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: todos
            - name: MYSQL_ROOT_PASSWORD
              value: secret
          image: mysql:5.7
          name: mysql
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: todo-mysql-data
      restartPolicy: Always
      volumes:
        - name: todo-mysql-data
          persistentVolumeClaim:
            claimName: todo-mysql-data
status: {}
